### ISSUE TITLE
Where is the data

### ISSUE THREAD

**Issue by poojamittal234** [Jdhaimson/NLP_CRT#1]
Hi,

I want to execute this project but wonder where is the data file for this?

Can some one please provide the data set used in this project  !!

Regards,
Pooja

**Comment by Jdhaimson** [comment]
Hi Pooja,

The exact dataset that this code was developed on is [proprietary Partners Healthcare data](https://rc.partners.org/research-apps-and-services/identify-subjects-request-data#getstarted) and is not available to the general public for patient privacy reasons. However, many of the techniques used are likely generalizable to data from most medical systems. One option to look into is the [mimic dataset](https://mimic.physionet.org/).

Best,
Josh
